CREATE PROCEDURE [dbo].[DepartamentosEliminar]
	@Id_Departamento INT
AS
	BEGIN
		SET NOCOUNT ON
		BEGIN TRANSACTION TRASA
			BEGIN TRY
				--METODO
				DELETE FROM Departamentos 
				WHERE Id_Departamento=@Id_Departamento

				COMMIT TRANSACTION TRASA
					SELECT 0 AS CodeError,'' AS MsgErr
			END TRY
			BEGIN CATCH
				SELECT ERROR_NUMBER() AS CodeError, ERROR_MESSAGE() AS MsgErr
				ROLLBACK TRANSACTION TRASA
			END CATCH
	END

